/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samples;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author ken
 */
public class SampleAppForm extends javax.swing.JFrame {

    /**
     * Creates new form SampleAppForm
     */
    public SampleAppForm() {
        initComponents();
        
        setListeners();
        
        pack();
        setLocationRelativeTo(null);
    }
    
    public void setListeners() {
        
        btnCalculate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               
                // check whether the is input
                if(textFieldDate.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Kindy Enter date to continue.",
                            "Message",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                // check whether there is two string with a comma
                if(!hasComma(textFieldDate.getText())) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Kindy Enter dates in required format separated wih commas.",
                            "Message",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                String[] dates = textFieldDate.getText().split(",");
                
                try {
                    System.out.println("output" +  dates[0] + " - " + dates[1]);
                    
                    MyDate date = new MyDate(dates[0]);
                    MyDate date2 = new MyDate(dates[1]);
                    
                    System.out.println("output" +  date + " - " + date2);
                    
                    int diff = new MyDateUtils().difference(date, date2);
                
                    System.out.println("diff" + diff);
                    
                    String output = "Input> " + dates[0] + "/t" +  dates[1] +" /n" +
                            "Output> " + dates[0] + "/t" +  dates[1] +" t" + diff;
                    
                    textAreaResults.setText(output);
 
                }catch(Exception e) {
//                    JOptionPane.showMessageDialog(rootPane,
//                            e.getMessage(),
//                            "Message",
//                            JOptionPane.ERROR_MESSAGE);
                }
            }
            
        });
    }
    
    private boolean hasComma(String param) {
        return param.contains(",");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResults = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Sample App to Calculate Date Difference");

        textFieldDate.setToolTipText("Enter Dates");

        jLabel2.setText("Enter two date in Format: DD MM YYYY, DD MM YYYY");

        btnCalculate.setText("Calculate Difference");

        textAreaResults.setEditable(false);
        textAreaResults.setColumns(20);
        textAreaResults.setRows(5);
        jScrollPane1.setViewportView(textAreaResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCalculate)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(textFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(textFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCalculate)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaResults;
    private javax.swing.JTextField textFieldDate;
    // End of variables declaration//GEN-END:variables
}
